spring:
  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/damda?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    driverClassName: org.mariadb.jdbc.Driver
    username: jealocal
    password: '1234'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: traveldamda@gmail.com
    password: ykwkqgphbwelthrb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
